from abc import ABC, abstractmethod

class BaseStorageProvider(ABC):
    async def put_resume(self, user_id: str, file_bytes: bytes, filename: str) -> str: ...
    async def put_recording(self, interview_id: str, audio_bytes: bytes) -> str: ...
    async def get_signed_url(self, path: str, expires_in: int = 3600) -> str: ...
