from abc import ABC, abstractmethod

class BaseLLMProvider(ABC):
    async def generate_questions(self, context: dict) -> list[dict]: ...
    async def evaluate_answer(self, question: dict, transcript: str, context: dict) -> dict: ...
    async def extract_skills(self, text: str, doc_type: str) -> dict: ...
    async def generate_roadmap(self, weak_concepts: list[str], role: str) -> dict: ...
